export const fgtTimezone = [
  "(GMT-12:00) Eniwetak, Kwajalein",
  "(GMT-11:00) Midway Island, Samoa",
  "(GMT-10:00) Hawaii",
  "(GMT-9:00) Alaska",
  "(GMT-8:00) Pacific Time (US & Canada)",
  "(GMT-7:00) Arizona",
  "(GMT-7:00) Mountain Time (US & Canada)",
  "(GMT-6:00) Central America",
  "(GMT-6:00) Central Time (US & Canada)",
  "(GMT-6:00) Mexico City",
  "(GMT-6:00) Saskatchewan",
  "(GMT-5:00) Bogota, Lima, Quito",
  "(GMT-5:00) Eastern Time (US & Canada)",
  "(GMT-5:00) Indiana (East)",
  "(GMT-4:00) Atlantic Time (Canada)",
  "(GMT-4:00) La Paz",
  "(GMT-4:00) Santiago",
  "(GMT-3:30) Newfoundland",
  "(GMT-3:00) Brasilia",
  "(GMT-3:00) Buenos Aires, Georgetown",
  "(GMT-3:00) Nuuk (Greenland)",
  "(GMT-2:00) Mid-Atlantic",
  "(GMT-1:00) Azores",
  "(GMT-1:00) Cape Verde Is",
  "(GMT) Casablanca, Monrovia",
  "(GMT) Greenwich Mean Time:Dublin, Edinburgh, Lisbon, London",
  "(GMT+1:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna",
  "(GMT+1:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague",
  "(GMT+1:00) Brussels, Copenhagen, Madrid, Paris",
  "(GMT+1:00) Sarajevo, Skopje, Sofija, Vilnius, Warsaw, Zagreb",
  "(GMT+1:00) West Central Africa",
  "(GMT+2:00) Athens, Istanbul, Minsk",
  "(GMT+2:00) Bucharest",
  "(GMT+2:00) Cairo",
  "(GMT+2:00) Harare, Pretoria",
  "(GMT+2:00) Helsinki, Riga,Tallinn",
  "(GMT+2:00) Jerusalem",
  "(GMT+3:00) Baghdad",
  "(GMT+3:00) Kuwait, Riyadh",
  "(GMT+3:00) Moscow, St.Petersburg, Volgograd",
  "(GMT+3:00) Nairobi",
  "(GMT+3:30) Tehran",
  "(GMT+4:00) Abu Dhabi, Muscat",
  "(GMT+4:00) Baku",
  "(GMT+4:30) Kabul",
  "(GMT+5:00) Ekaterinburg",
  "(GMT+5:00) Islamabad, Karachi,Tashkent",
  "(GMT+5:30) Calcutta, Chennai, Mumbai, New Delhi",
  "(GMT+5:45) Kathmandu",
  "(GMT+6:00) Almaty, Novosibirsk",
  "(GMT+6:00) Astana, Dhaka",
  "(GMT+6:00) Sri Jayawardenapura",
  "(GMT+6:30) Rangoon",
  "(GMT+7:00) Bangkok, Hanoi, Jakarta",
  "(GMT+7:00) Krasnoyarsk",
  "(GMT+8:00) Beijing,ChongQing, HongKong,Urumqi",
  "(GMT+8:00) Irkutsk, Ulaanbaatar",
  "(GMT+8:00) Kuala Lumpur, Singapore",
  "(GMT+8:00) Perth",
  "(GMT+8:00) Taipei",
  "(GMT+9:00) Osaka, Sapporo, Tokyo, Seoul",
  "(GMT+9:00) Yakutsk",
  "(GMT+9:30) Adelaide",
  "(GMT+9:30) Darwin",
  "(GMT+10:00) Brisbane",
  "(GMT+10:00) Canberra, Melbourne, Sydney",
  "(GMT+10:00) Guam, Port Moresby",
  "(GMT+10:00) Hobart",
  "(GMT+10:00) Vladivostok",
  "(GMT+11:00) Magadan",
  "(GMT+11:00) Solomon Is., New Caledonia",
  "(GMT+12:00) Auckland, Wellington",
  "(GMT+12:00) Fiji, Kamchatka, Marshall Is",
  "(GMT+13:00) Nuku'alofa",
  "(GMT-4:30) Caracas",
  "(GMT+1:00) Namibia",
  "(GMT-5:00) Brazil-Acre)",
  "(GMT-4:00) Brazil-West",
  "(GMT-3:00) Brazil-East",
  "(GMT-2:00) Brazil-DeNoronha",
];

export const srxTimezone = [
  "Africa/Abidjan",
  "Africa/Accra",
  "Africa/Addis_Ababa",
  "Africa/Algiers",
  "Africa/Asmera",
  "Africa/Bamako",
  "Africa/Bangui",
  "Africa/Banjul",
  "Africa/Bissau",
  "Africa/Blantyre",
  "Africa/Brazzaville",
  "Africa/Bujumbura",
  "Africa/Cairo",
  "Africa/Casablanca",
  "Africa/Ceuta",
  "Africa/Conakry",
  "Africa/Dakar",
  "Africa/Dar_es_Salaam",
  "Africa/Djibouti",
  "Africa/Douala",
  "Africa/El_Aaiun",
  "Africa/Freetown",
  "Africa/Gaborone",
  "Africa/Harare",
  "Africa/Johannesburg",
  "Africa/Kampala",
  "Africa/Khartoum",
  "Africa/Kigali",
  "Africa/Kinshasa",
  "Africa/Lagos",
  "Africa/Libreville",
  "Africa/Lome",
  "Africa/Luanda",
  "Africa/Lubumbashi",
  "Africa/Lusaka",
  "Africa/Malabo",
  "Africa/Maputo",
  "Africa/Maseru",
  "Africa/Mbabane",
  "Africa/Mogadishu",
  "Africa/Monrovia",
  "Africa/Nairobi",
  "Africa/Ndjamena",
  "Africa/Niamey",
  "Africa/Nouakchott",
  "Africa/Ouagadougou",
  "Africa/Porto-Novo",
  "Africa/Sao_Tome",
  "Africa/Timbuktu",
  "Africa/Tripoli",
  "Africa/Tunis",
  "Africa/Windhoek",
  "America/Adak",
  "America/Anchorage",
  "America/Anguilla",
  "America/Antigua",
  "America/Aruba",
  "America/Asuncion",
  "America/Barbados",
  "America/Belize",
  "America/Bogota",
  "America/Boise",
  "America/Buenos_Aires",
  "America/Caracas",
  "America/Catamarca",
  "America/Cayenne",
  "America/Cayman",
  "America/Chicago",
  "America/Cordoba",
  "America/Costa_Rica",
  "America/Cuiaba",
  "America/Curacao",
  "America/Dawson",
  "America/Dawson_Creek",
  "America/Denver",
  "America/Detroit",
  "America/Dominica",
  "America/Edmonton",
  "America/El_Salvador",
  "America/Ensenada",
  "America/Fortaleza",
  "America/Glace_Bay",
  "America/Godthab",
  "America/Goose_Bay",
  "America/Grand_Turk",
  "America/Grenada",
  "America/Guadeloupe",
  "America/Guatemala",
  "America/Guayaquil",
  "America/Guyana",
  "America/Halifax",
  "America/Havana",
  "America/Indiana/Knox",
  "America/Indiana/Marengo",
  "America/Indiana/Vevay",
  "America/Indianapolis",
  "America/Inuvik",
  "America/Iqaluit",
  "America/Jamaica",
  "America/Jujuy",
  "America/Juneau",
  "America/La_Paz",
  "America/Lima",
  "America/Los_Angeles",
  "America/Louisville",
  "America/Maceio",
  "America/Managua",
  "America/Manaus",
  "America/Martinique",
  "America/Mazatlan",
  "America/Mendoza",
  "America/Menominee",
  "America/Mexico_City",
  "America/Miquelon",
  "America/Montevideo",
  "America/Montreal",
  "America/Montserrat",
  "America/Nassau",
  "America/New_York",
  "America/Nipigon",
  "America/Nome",
  "America/Noronha",
  "America/Panama",
  "America/Pangnirtung",
  "America/Paramaribo",
  "America/Phoenix",
  "America/Port-au-Prince",
  "America/Port_of_Spain",
  "America/Porto_Acre",
  "America/Puerto_Rico",
  "America/Rainy_River",
  "America/Rankin_Inlet",
  "America/Regina",
  "America/Rosario",
  "America/Santiago",
  "America/Santo_Domingo",
  "America/Sao_Paulo",
  "America/Scoresbysund",
  "America/Shiprock",
  "America/St_Johns",
  "America/St_Kitts",
  "America/St_Lucia",
  "America/St_Thomas",
  "America/St_Vincent",
  "America/Swift_Current",
  "America/Tegucigalpa",
  "America/Thule",
  "America/Thunder_Bay",
  "America/Tijuana",
  "America/Tortola",
  "America/Vancouver",
  "America/Whitehorse",
  "America/Winnipeg",
  "America/Yakutat",
  "America/Yellowknife",
  "Antarctica/Casey",
  "Antarctica/DumontDUrville",
  "Antarctica/Mawson",
  "Antarctica/McMurdo",
  "Antarctica/Palmer",
  "Antarctica/South_Pole",
  "Arctic/Longyearbyen",
  "Asia/Aden",
  "Asia/Alma-Ata",
  "Asia/Amman",
  "Asia/Anadyr",
  "Asia/Aqtau",
  "Asia/Aqtobe",
  "Asia/Ashkhabad",
  "Asia/Baghdad",
  "Asia/Bahrain",
  "Asia/Baku",
  "Asia/Bangkok",
  "Asia/Beirut",
  "Asia/Bishkek",
  "Asia/Brunei",
  "Asia/Chungking",
  "Asia/Colombo",
  "Asia/Dacca",
  "Asia/Damascus",
  "Asia/Dubai",
  "Asia/Dushanbe",
  "Asia/Gaza",
  "Asia/Harbin",
  "Asia/Hong_Kong",
  "Asia/Irkutsk",
  "Asia/Ishigaki",
  "Asia/Jakarta",
  "Asia/Jayapura",
  "Asia/Jerusalem",
  "Asia/Kabul",
  "Asia/Kamchatka",
  "Asia/Karachi",
  "Asia/Kashgar",
  "Asia/Katmandu",
  "Asia/Kolkata",
  "Asia/Krasnoyarsk",
  "Asia/Kuala_Lumpur",
  "Asia/Kuching",
  "Asia/Kuwait",
  "Asia/Macao",
  "Asia/Magadan",
  "Asia/Manila",
  "Asia/Muscat",
  "Asia/Nicosia",
  "Asia/Novosibirsk",
  "Asia/Omsk",
  "Asia/Phnom_Penh",
  "Asia/Pyongyang",
  "Asia/Qatar",
  "Asia/Rangoon",
  "Asia/Riyadh",
  "Asia/Saigon",
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Singapore",
  "Asia/Taipei",
  "Asia/Tashkent",
  "Asia/Tbilisi",
  "Asia/Tehran",
  "Asia/Thimbu",
  "Asia/Tokyo",
  "Asia/Ujung_Pandang",
  "Asia/Ulan_Bator",
  "Asia/Urumqi",
  "Asia/Vientiane",
  "Asia/Vladivostok",
  "Asia/Yakutsk",
  "Asia/Yekaterinburg",
  "Asia/Yerevan",
  "Atlantic/Azores",
  "Atlantic/Bermuda",
  "Atlantic/Canary",
  "Atlantic/Cape_Verde",
  "Atlantic/Faeroe",
  "Atlantic/Jan_Mayen",
  "Atlantic/Madeira",
  "Atlantic/Reykjavik",
  "Atlantic/South_Georgia",
  "Atlantic/St_Helena",
  "Atlantic/Stanley",
  "Australia/Adelaide",
  "Australia/Brisbane",
  "Australia/Broken_Hill",
  "Australia/Darwin",
  "Australia/Hobart",
  "Australia/Lindeman",
  "Australia/Lord_Howe",
  "Australia/Melbourne",
  "Australia/Perth",
  "Australia/Sydney",
  "Europe/Amsterdam",
  "Europe/Andorra",
  "Europe/Athens",
  "Europe/Belfast",
  "Europe/Belgrade",
  "Europe/Berlin",
  "Europe/Bratislava",
  "Europe/Brussels",
  "Europe/Bucharest",
  "Europe/Budapest",
  "Europe/Chisinau",
  "Europe/Copenhagen",
  "Europe/Dublin",
  "Europe/Gibraltar",
  "Europe/Helsinki",
  "Europe/Istanbul",
  "Europe/Kaliningrad",
  "Europe/Kiev",
  "Europe/Lisbon",
  "Europe/Ljubljana",
  "Europe/London",
  "Europe/Luxembourg",
  "Europe/Madrid",
  "Europe/Malta",
  "Europe/Minsk",
  "Europe/Monaco",
  "Europe/Moscow",
  "Europe/Oslo",
  "Europe/Paris",
  "Europe/Prague",
  "Europe/Riga",
  "Europe/Rome",
  "Europe/Samara",
  "Europe/San_Marino",
  "Europe/Sarajevo",
  "Europe/Simferopol",
  "Europe/Skopje",
  "Europe/Sofia",
  "Europe/Stockholm",
  "Europe/Tallinn",
  "Europe/Tirane",
  "Europe/Vaduz",
  "Europe/Vatican",
  "Europe/Vienna",
  "Europe/Vilnius",
  "Europe/Warsaw",
  "Europe/Zagreb",
  "Europe/Zurich",
  "Indian/Antananarivo",
  "Indian/Chagos",
  "Indian/Christmas",
  "Indian/Cocos",
  "Indian/Comoro",
  "Indian/Kerguelen",
  "Indian/Mahe",
  "Indian/Maldives",
  "Indian/Mauritius",
  "Indian/Mayotte",
  "Indian/Reunion",
  "Pacific/Apia",
  "Pacific/Auckland",
  "Pacific/Chatham",
  "Pacific/Easter",
  "Pacific/Efate",
  "Pacific/Enderbury",
  "Pacific/Fakaofo",
  "Pacific/Fiji",
  "Pacific/Funafuti",
  "Pacific/Galapagos",
  "Pacific/Gambier",
  "Pacific/Guadalcanal",
  "Pacific/Guam",
  "Pacific/Honolulu",
  "Pacific/Johnston",
  "Pacific/Kiritimati",
  "Pacific/Kosrae",
  "Pacific/Kwajalein",
  "Pacific/Majuro",
  "Pacific/Marquesas",
  "Pacific/Midway",
  "Pacific/Nauru",
  "Pacific/Niue",
  "Pacific/Norfolk",
  "Pacific/Noumea",
  "Pacific/Pago_Pago",
  "Pacific/Palau",
  "Pacific/Pitcairn",
  "Pacific/Ponape",
  "Pacific/Port_Moresby",
  "Pacific/Rarotonga",
  "Pacific/Saipan",
  "Pacific/Tahiti",
  "Pacific/Tarawa",
  "Pacific/Tongatapu",
  "Pacific/Truk",
  "Pacific/Wake",
  "Pacific/Wallis",
  "Pacific/Yap",
];
